### ISSUE TITLE
Add Extra Shopping Sections on the Homepage

### ISSUE THREAD

**Issue by Rutam21** [ArmanChand/Hortus_Basket#1]
# What
The shopping homepage misses two major shopping categories i.e., SNACKS and CHOCOLATES. This needs to be added.

# How
Add these two categories to the Homepage by making suitable changes in the `index.html` file and submitting a PR.

**Comment by Rutam21** [comment]
@ArmanChand Please assign this issue to me. Thanks

**Comment by ArmanChand** [comment]
@Rutam21 , assigned to you. Thank you for the contribution
